/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    prestations: Prestation;
    planning: Planning;
    tarifs: Tarif;
    faq: Faq;
    avis: Avi;
    equipe: Equipe;
    articles: Article;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    prestations: PrestationsSelect<false> | PrestationsSelect<true>;
    planning: PlanningSelect<false> | PlanningSelect<true>;
    tarifs: TarifsSelect<false> | TarifsSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    avis: AvisSelect<false> | AvisSelect<true>;
    equipe: EquipeSelect<false> | EquipeSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    parametres: Parametre;
  };
  globalsSelect: {
    parametres: ParametresSelect<false> | ParametresSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Fiches activités : mercredis sportifs, stages, anniversaire, cours par tranche d’âge.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestations".
 */
export interface Prestation {
  id: number;
  titre: string;
  /**
   * Ex. : cours-3-5-ans → /nos-prestations/cours-3-5-ans. Ne pas modifier une fois la page en ligne.
   */
  slug: string;
  /**
   * Affichée en pastille sur l’image. Ex. : « 3 – 5 ans », « Tous âges ».
   */
  age: string;
  /**
   * Une phrase, reprise sous le titre du hero et sur les cartes.
   */
  accroche: string;
  /**
   * Paragraphe de présentation (bloc « Le principe » de la fiche).
   */
  intro: string;
  /**
   * Liste à puces cochées de la fiche (3 ou 4 lignes courtes).
   */
  benefices?:
    | {
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Uniquement pour les 4 cours par tranche d’âge : le détail des activités pratiquées. Chaque activité a sa propre page /nos-prestations/[cours]/[activité], une carte sur la fiche du cours et une entrée du sous-menu « Nos activités ».
   */
  disciplines?:
    | {
        nom: string;
        /**
         * Segment d’URL de la page de l’activité. Ex. : kid-gym-et-dance → /nos-prestations/cours-3-5-ans/kid-gym-et-dance. Laisser vide pour le déduire du nom. Ne pas modifier une fois la page en ligne.
         */
        slug?: string | null;
        /**
         * Résumé court : sous-titre du hero de la page de l’activité, texte de sa carte sur la fiche du cours.
         */
        description: string;
        /**
         * Corps de la page de l’activité : 2 paragraphes. Vide, le texte de src/data/prestations.ts est servi.
         */
        intro?:
          | {
              texte: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Liste à puces cochées de la page (3 à 5 lignes courtes).
         */
        benefices?:
          | {
              texte: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Un paragraphe : à quels enfants cette activité s’adresse.
         */
        pourQui?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. : « 95 €/mois », « À partir de 29,90 €/mois ».
   */
  prix: string;
  /**
   * Phrase du bloc « Créneaux ». Si elle contient « voir le planning », ces mots deviennent un lien vers /planning.
   */
  creneauxTexte: string;
  /**
   * Utilisé dans la meta description et les données structurées de la fiche.
   */
  motCle: string;
  /**
   * Optionnelle : sans photo, le visuel actuel du site est conservé.
   */
  image?: (number | null) | Media;
  /**
   * Ordre dans la mosaïque, le footer et le sitemap.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrit l’image pour l’accessibilité et le référencement.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Un créneau par ligne. L’ordre s’applique à l’intérieur de chaque journée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning".
 */
export interface Planning {
  id: number;
  jour: 'Lundi' | 'Mardi' | 'Mercredi' | 'Jeudi' | 'Vendredi' | 'Samedi';
  /**
   * Ex. : Salle Kid, Salle Cross, Salle Fitness, Bulle.
   */
  salle: string;
  /**
   * Ex. : 10h30, 17h, 9h15.
   */
  heure: string;
  activite: string;
  /**
   * Optionnelle. Elle affiche la pastille d’âge et fait remonter le créneau dans le formulaire des fiches activités.
   */
  age?: ('10-36 mois' | '3-5 ans' | '6-14 ans') | null;
  /**
   * Ordre du créneau dans sa journée.
   */
  ordre?: number | null;
  /**
   * Décoché : le créneau disparaît du site.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs".
 */
export interface Tarif {
  id: number;
  /**
   * Détermine le groupe dans lequel la carte apparaît sur la page Tarifs.
   */
  type: 'abonnement' | 'prestation';
  titre: string;
  /**
   * Ex. : « 29,90 €/mois », « 190 € », « 35 €/jour ou 150 €/semaine ».
   */
  prix: string;
  /**
   * Mention sous le prix. Ex. : « Engagement 10 mois ».
   */
  detail: string;
  /**
   * Badge « La plus choisie » et bordure magenta. Une seule carte à la fois.
   */
  enAvant?: boolean | null;
  /**
   * Ordre dans son groupe (abonnements ou prestations).
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  reponse: string;
  /**
   * Si la réponse contient les mots « page tarifs », ils deviennent un lien vers /tarifs.
   */
  lienTarifs?: boolean | null;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Avis recopiés tels quels (verbatim). L’ordre est celui d’affichage sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avis".
 */
export interface Avi {
  id: number;
  texte: string;
  /**
   * Attribution affichée sous l’avis. Laisser la mention neutre par défaut si le parent n’a pas donné son nom.
   */
  auteur?: string | null;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe".
 */
export interface Equipe {
  id: number;
  nom: string;
  /**
   * Monogramme affiché tant qu’il n’y a pas de photo. Ex. : « ML ».
   */
  initiales: string;
  bio: string;
  /**
   * Optionnelle : sans photo, les initiales sont affichées dans un rond marine.
   */
  photo?: (number | null) | Media;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  titre: string;
  /**
   * Ex. : a-quel-age-sport-enfant → /blog/a-quel-age-sport-enfant.
   */
  slug: string;
  /**
   * Résumé des cartes du blog, également utilisé en meta description.
   */
  excerpt: string;
  date: string;
  /**
   * Le corps de l’article, bloc par bloc, dans l’ordre de lecture.
   */
  blocs?:
    | {
        t: 'p' | 'h2';
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionnelle : sans image, le visuel actuel de l’article est conservé.
   */
  image?: (number | null) | Media;
  /**
   * Décoché : l’article n’apparaît plus sur le site.
   */
  publie?: boolean | null;
  /**
   * Ordre de référence (blocs « À lire aussi », sitemap). Le hub du blog et l’accueil affichent toujours les articles du plus récent au plus ancien.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editeur';
  nom?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'prestations';
        value: number | Prestation;
      } | null)
    | ({
        relationTo: 'planning';
        value: number | Planning;
      } | null)
    | ({
        relationTo: 'tarifs';
        value: number | Tarif;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'avis';
        value: number | Avi;
      } | null)
    | ({
        relationTo: 'equipe';
        value: number | Equipe;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestations_select".
 */
export interface PrestationsSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  age?: T;
  accroche?: T;
  intro?: T;
  benefices?:
    | T
    | {
        texte?: T;
        id?: T;
      };
  disciplines?:
    | T
    | {
        nom?: T;
        slug?: T;
        description?: T;
        intro?:
          | T
          | {
              texte?: T;
              id?: T;
            };
        benefices?:
          | T
          | {
              texte?: T;
              id?: T;
            };
        pourQui?: T;
        id?: T;
      };
  prix?: T;
  creneauxTexte?: T;
  motCle?: T;
  image?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning_select".
 */
export interface PlanningSelect<T extends boolean = true> {
  jour?: T;
  salle?: T;
  heure?: T;
  activite?: T;
  age?: T;
  ordre?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs_select".
 */
export interface TarifsSelect<T extends boolean = true> {
  type?: T;
  titre?: T;
  prix?: T;
  detail?: T;
  enAvant?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  reponse?: T;
  lienTarifs?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avis_select".
 */
export interface AvisSelect<T extends boolean = true> {
  texte?: T;
  auteur?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe_select".
 */
export interface EquipeSelect<T extends boolean = true> {
  nom?: T;
  initiales?: T;
  bio?: T;
  photo?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  excerpt?: T;
  date?: T;
  blocs?:
    | T
    | {
        t?: T;
        texte?: T;
        id?: T;
      };
  image?: T;
  publie?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  nom?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres".
 */
export interface Parametre {
  id: number;
  coordonnees?: {
    telephone?: string | null;
    /**
     * Format international. Ex. : tel:+33247444143
     */
    telephoneHref?: string | null;
    email?: string | null;
    /**
     * Ex. : mailto:kidfitnessrochecorbon@gmail.com
     */
    emailHref?: string | null;
    adresse?: string | null;
    /**
     * Lien Google Maps ouvert au clic sur l’adresse.
     */
    adresseHref?: string | null;
    /**
     * URL « output=embed » de Google Maps, affichée dans l’iframe du plan.
     */
    mapsEmbedUrl?: string | null;
    mapTitle?: string | null;
  };
  /**
   * Une seule ligne. Le footer coupe l’affichage sur les séparateurs « · ». Ex. : « Lun–Ven : 9h00–19h30 (sans coupure) · Samedi : 9h30–12h30 ».
   */
  horaires?: string | null;
  /**
   * Destination du bouton « S’inscrire ». Réservé : le bouton est rendu dans l’en-tête (composant interactif) et suit encore la valeur du code (src/data/site.ts) tant que l’inscription en ligne n’est pas branchée.
   */
  inscriptionUrl?: string | null;
  /**
   * Lien ouvert par les boutons « S’inscrire » de la landing catalogue. « # » tant que le calendrier n’est pas fourni.
   */
  crmInscriptionUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres_select".
 */
export interface ParametresSelect<T extends boolean = true> {
  coordonnees?:
    | T
    | {
        telephone?: T;
        telephoneHref?: T;
        email?: T;
        emailHref?: T;
        adresse?: T;
        adresseHref?: T;
        mapsEmbedUrl?: T;
        mapTitle?: T;
      };
  horaires?: T;
  inscriptionUrl?: T;
  crmInscriptionUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}