/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    planning: Planning;
    prestations: Prestation;
    tarifs: Tarif;
    articles: Article;
    faq: Faq;
    avis: Avi;
    equipe: Equipe;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    planning: PlanningSelect<false> | PlanningSelect<true>;
    prestations: PrestationsSelect<false> | PrestationsSelect<true>;
    tarifs: TarifsSelect<false> | TarifsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    faq: FaqSelect<false> | FaqSelect<true>;
    avis: AvisSelect<false> | AvisSelect<true>;
    equipe: EquipeSelect<false> | EquipeSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    parametres: Parametre;
  };
  globalsSelect: {
    parametres: ParametresSelect<false> | ParametresSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Les créneaux de la semaine type, affichés sur la page Planning et sur les pages des cours. Un créneau par ligne ; l’ordre s’applique à l’intérieur de chaque journée.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning".
 */
export interface Planning {
  id: number;
  jour: 'Lundi' | 'Mardi' | 'Mercredi' | 'Jeudi' | 'Vendredi' | 'Samedi';
  /**
   * Heure de début. Ex. : 10h30, 17h, 9h15.
   */
  heure: string;
  /**
   * Elle fixe la hauteur du bloc dans le calendrier de la semaine. 60 minutes par défaut.
   */
  duree?: number | null;
  /**
   * Nom du cours tel qu’il s’affiche dans le calendrier. Écrivez-le toujours de la même façon : il sert aussi à retrouver les horaires d’un cours sur sa page.
   */
  activite: string;
  /**
   * Ex. : Salle Kid, Salle Cross, Salle Fitness, Bulle.
   */
  salle: string;
  /**
   * Optionnelle. Elle donne sa couleur et sa pastille d’âge au créneau, ouvre le bon lien de réservation et propose le créneau dans le formulaire des fiches activités.
   */
  age?: ('10-36 mois' | '3-5 ans' | '6-14 ans') | null;
  /**
   * Ordre du créneau dans sa journée.
   */
  ordre?: number | null;
  /**
   * Décoché : le créneau disparaît du site.
   */
  actif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les 7 fiches du menu « Nos activités » : Mercredis Sportifs, stages, anniversaire et les 4 cours par tranche d’âge. Chaque fiche est une page du site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestations".
 */
export interface Prestation {
  id: number;
  titre: string;
  /**
   * Affichée en pastille sur l’image. Ex. : « 3 – 5 ans », « Tous âges ».
   */
  age: string;
  /**
   * Ex. : « 95 €/mois », « À partir de 29,90 €/mois ».
   */
  prix: string;
  /**
   * Une phrase, reprise sous le titre en haut de la page et sur les cartes.
   */
  accroche: string;
  /**
   * Paragraphe de présentation (bloc « Le principe » de la fiche).
   */
  intro: string;
  /**
   * Liste à puces cochées de la fiche (3 ou 4 lignes courtes).
   */
  benefices?:
    | {
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Phrase du bloc « Créneaux ». Si elle contient « voir le planning », ces mots deviennent un lien vers la page Planning.
   */
  creneauxTexte: string;
  /**
   * Optionnelle : sans photo, le visuel actuel du site est conservé.
   */
  image?: (number | null) | Media;
  /**
   * Les cours pratiqués dans cette tranche d’âge. Chaque cours a sa propre page, une carte sur la fiche de la tranche et une entrée dans le sous-menu « Nos activités » du site.
   */
  disciplines?:
    | {
        nom: string;
        /**
         * Durée d’une séance, affichée en pastille (« 45 min », « 1h ») sur la fiche de la tranche et sur la page du cours. Vide : aucune pastille.
         */
        duree?: number | null;
        /**
         * Résumé court : sous-titre en haut de la page du cours et texte de sa carte sur la fiche de la tranche.
         */
        description: string;
        /**
         * Texte de la page du cours, en 2 paragraphes. Vide : le texte actuel du site est conservé.
         */
        intro?:
          | {
              texte: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Liste à puces cochées de la page (3 à 5 lignes courtes).
         */
        benefices?:
          | {
              texte: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Un paragraphe : à quels enfants ce cours s’adresse.
         */
        pourQui?: string | null;
        /**
         * Fin de l’adresse de la page du cours, après celle de la tranche. Ex. : gym-et-dance donne kidsportclub.fr/nos-prestations/cours-3-5-ans/gym-et-dance. Vide : elle est déduite du nom. Ne plus la modifier une fois la page en ligne.
         */
        slug?: string | null;
        /**
         * Nom du cours tel qu’il est écrit dans le planning, pour afficher ses horaires sur sa page. S’il porte plusieurs noms dans le planning, séparez-les par une barre verticale. Ex. : Pompom|Pompom Girl.
         */
        activitePlanning?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Petite note affichée sous la grille des cours. Ex. : « *Multisports : football, rugby, basket… ».
   */
  noteDisciplines?: string | null;
  /**
   * Optionnelle, affichée au-dessus des étapes. Ex. : « Même principe que les Mercredis Sportifs, avec un accueil dès 8h00. »
   */
  derouleIntro?: string | null;
  /**
   * Les étapes de la journée, dans l’ordre. Liste vide : la section n’est pas affichée sur la fiche.
   */
  deroule?:
    | {
        /**
         * Ex. : « 7h30 – 10h00 ».
         */
        horaire: string;
        titre: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Phrase affichée sous les étapes, en italique.
   */
  derouleNote?: string | null;
  /**
   * Fin de l’adresse de la page sur le site. Ex. : cours-3-5-ans donne kidsportclub.fr/nos-prestations/cours-3-5-ans. En minuscules, sans accents ni espaces (mots séparés par des tirets). Ne plus la modifier une fois la page en ligne.
   */
  slug: string;
  /**
   * Expression que les parents tapent dans Google pour trouver cette activité. Elle est reprise dans le résumé de la page destiné aux moteurs de recherche.
   */
  motCle: string;
  /**
   * Ordre d’affichage sur la page Nos activités et dans le pied de page.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les photos utilisées sur le site : activités, équipe, articles, avis. Le texte alternatif décrit chaque photo aux personnes malvoyantes et à Google.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Décrivez la photo en une phrase. Ex. : « Enfants en cours de gym dans la salle Kid ».
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Les formules affichées sur la page Tarifs : les abonnements aux cours d’un côté, les autres prestations de l’autre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs".
 */
export interface Tarif {
  id: number;
  titre: string;
  /**
   * Ex. : « 29,90 €/mois », « 190 € », « 35 €/jour ou 150 €/semaine ».
   */
  prix: string;
  /**
   * Détermine le groupe dans lequel la formule apparaît sur la page Tarifs.
   */
  type: 'abonnement' | 'prestation';
  /**
   * Mention sous le prix. Ex. : « Engagement 10 mois ».
   */
  detail: string;
  /**
   * Points listés sous le prix, avec une coche magenta. Affichés uniquement sur les cartes complètes (formules prioritaires).
   */
  avantages?:
    | {
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Pastille en tête de carte. Vide : éclair par défaut.
   */
  icone?: ('zap' | 'layers2' | 'layers3' | 'carte' | 'calendrier' | 'vacances') | null;
  /**
   * Coché : la formule est présentée en carte complète dans « Nos formules » sur la page Tarifs. Décoché : elle apparaît en ligne compacte dans « Autres formules ».
   */
  prioritaire?: boolean | null;
  /**
   * Badge « La plus choisie » et bordure magenta. Une seule carte à la fois.
   */
  enAvant?: boolean | null;
  /**
   * Ordre dans son groupe (abonnements ou prestations).
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les articles du blog, aussi mis en avant sur l’accueil (« Actus & conseils »). Décochez « Publié » pour retirer un article du site sans le supprimer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  titre: string;
  /**
   * Fin de l’adresse de l’article sur le site. Ex. : a-quel-age-sport-enfant donne kidsportclub.fr/blog/a-quel-age-sport-enfant. En minuscules, sans accents ni espaces (mots séparés par des tirets). Ne plus la modifier une fois l’article publié.
   */
  slug: string;
  /**
   * Résumé affiché sur les cartes du blog et repris par Google sous le titre de la page.
   */
  excerpt: string;
  date: string;
  /**
   * Le corps de l’article, bloc par bloc, dans l’ordre de lecture.
   */
  blocs?:
    | {
        t: 'p' | 'h2';
        texte: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optionnelle : sans image, le visuel actuel de l’article est conservé.
   */
  image?: (number | null) | Media;
  /**
   * Décoché : l’article n’apparaît plus sur le site.
   */
  publie?: boolean | null;
  /**
   * Ordre des suggestions « À lire aussi ». Le blog et l’accueil affichent toujours les articles du plus récent au plus ancien.
   */
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les questions fréquentes de la page FAQ, dans l’ordre d’affichage. Quelques-unes sont aussi reprises sur l’accueil.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface Faq {
  id: number;
  question: string;
  reponse: string;
  /**
   * Si la réponse contient les mots « page tarifs », ils deviennent un lien vers la page Tarifs.
   */
  lienTarifs?: boolean | null;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Avis de parents recopiés mot pour mot depuis Google. L’ordre est celui de l’affichage sur le site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avis".
 */
export interface Avi {
  id: number;
  texte: string;
  /**
   * Nom du parent tel qu’il apparaît sur son avis Google (prénom en premier, casse propre).
   */
  auteur?: string | null;
  /**
   * Chemin d’une photo déposée dans public/assets/ksc/avis (ex. /assets/ksc/avis/celine.webp). Vide = avatar illustré.
   */
  photo?: string | null;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les coachs et animateurs présentés sur les pages Qui sommes-nous et Séance d’essai. Sans photo, leurs initiales s’affichent dans un rond.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe".
 */
export interface Equipe {
  id: number;
  nom: string;
  /**
   * Affichées dans un rond tant qu’il n’y a pas de photo. Ex. : « ML ».
   */
  initiales: string;
  bio: string;
  /**
   * Optionnelle : sans photo, les initiales sont affichées dans un rond marine.
   */
  photo?: (number | null) | Media;
  ordre?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Les comptes qui peuvent se connecter à cet espace de gestion.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Admin : gestion complète, comptes compris. Éditeur : gestion du contenu du site.
   */
  role: 'admin' | 'editeur';
  /**
   * Utilisé pour vous saluer sur l’accueil de cet espace.
   */
  nom?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'planning';
        value: number | Planning;
      } | null)
    | ({
        relationTo: 'prestations';
        value: number | Prestation;
      } | null)
    | ({
        relationTo: 'tarifs';
        value: number | Tarif;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'faq';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'avis';
        value: number | Avi;
      } | null)
    | ({
        relationTo: 'equipe';
        value: number | Equipe;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "planning_select".
 */
export interface PlanningSelect<T extends boolean = true> {
  jour?: T;
  heure?: T;
  duree?: T;
  activite?: T;
  salle?: T;
  age?: T;
  ordre?: T;
  actif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prestations_select".
 */
export interface PrestationsSelect<T extends boolean = true> {
  titre?: T;
  age?: T;
  prix?: T;
  accroche?: T;
  intro?: T;
  benefices?:
    | T
    | {
        texte?: T;
        id?: T;
      };
  creneauxTexte?: T;
  image?: T;
  disciplines?:
    | T
    | {
        nom?: T;
        duree?: T;
        description?: T;
        intro?:
          | T
          | {
              texte?: T;
              id?: T;
            };
        benefices?:
          | T
          | {
              texte?: T;
              id?: T;
            };
        pourQui?: T;
        slug?: T;
        activitePlanning?: T;
        id?: T;
      };
  noteDisciplines?: T;
  derouleIntro?: T;
  deroule?:
    | T
    | {
        horaire?: T;
        titre?: T;
        description?: T;
        id?: T;
      };
  derouleNote?: T;
  slug?: T;
  motCle?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tarifs_select".
 */
export interface TarifsSelect<T extends boolean = true> {
  titre?: T;
  prix?: T;
  type?: T;
  detail?: T;
  avantages?:
    | T
    | {
        texte?: T;
        id?: T;
      };
  icone?: T;
  prioritaire?: T;
  enAvant?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  excerpt?: T;
  date?: T;
  blocs?:
    | T
    | {
        t?: T;
        texte?: T;
        id?: T;
      };
  image?: T;
  publie?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq_select".
 */
export interface FaqSelect<T extends boolean = true> {
  question?: T;
  reponse?: T;
  lienTarifs?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "avis_select".
 */
export interface AvisSelect<T extends boolean = true> {
  texte?: T;
  auteur?: T;
  photo?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "equipe_select".
 */
export interface EquipeSelect<T extends boolean = true> {
  nom?: T;
  initiales?: T;
  bio?: T;
  photo?: T;
  ordre?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  nom?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Coordonnées, horaires et liens utilisés partout sur le site : pied de page, page Contact, séance d’essai, pages de publicité.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres".
 */
export interface Parametre {
  id: number;
  coordonnees?: {
    /**
     * Numéro affiché sur le site. Le lien pour appeler d’un clic est créé automatiquement à partir de ce numéro.
     */
    telephone?: string | null;
    /**
     * Adresse affichée sur le site. Le lien pour écrire d’un clic est créé automatiquement à partir de cette adresse.
     */
    email?: string | null;
    /**
     * Adresse postale du club, telle qu’elle s’affiche sur le site.
     */
    adresse?: string | null;
    /**
     * Calculé automatiquement à partir du téléphone affiché : laissez ce champ vide.
     */
    telephoneHref?: string | null;
    /**
     * Calculé automatiquement à partir de l’email affiché : laissez ce champ vide.
     */
    emailHref?: string | null;
    /**
     * Page Google Maps ouverte quand on clique sur l’adresse.
     */
    adresseHref?: string | null;
    /**
     * Lien de la carte Google Maps affichée sur la page Contact et les pages de publicité.
     */
    mapsEmbedUrl?: string | null;
    /**
     * Nom de la carte, lu aux personnes malvoyantes. Ex. : « Plan | Kid Sport Club Rochecorbon ».
     */
    mapTitle?: string | null;
  };
  /**
   * Une seule ligne. Séparez les jours par un point médian « · » : le pied de page passe à la ligne à cet endroit. Ex. : « Lun–Ven : 9h00–19h30 (sans coupure) · Samedi : 9h30–12h30 ».
   */
  horaires?: string | null;
  inscriptionUrl?: string | null;
  /**
   * Lien ouvert par les boutons « S’inscrire » de la page catalogue utilisée pour les publicités. Laissez « # » tant que le calendrier n’est pas fourni.
   */
  crmInscriptionUrl?: string | null;
  /**
   * Chaque créneau du calendrier de la semaine ouvre le lien de sa tranche d’âge. Un créneau sans tranche d’âge ouvre le lien 6-14 ans.
   */
  reservation?: {
    url1036?: string | null;
    url35?: string | null;
    url614?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "parametres_select".
 */
export interface ParametresSelect<T extends boolean = true> {
  coordonnees?:
    | T
    | {
        telephone?: T;
        email?: T;
        adresse?: T;
        telephoneHref?: T;
        emailHref?: T;
        adresseHref?: T;
        mapsEmbedUrl?: T;
        mapTitle?: T;
      };
  horaires?: T;
  inscriptionUrl?: T;
  crmInscriptionUrl?: T;
  reservation?:
    | T
    | {
        url1036?: T;
        url35?: T;
        url614?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}